
platform :ios, '8.0'

target 'TuyaSmartSweeperKit_Example' do
  pod 'TuyaSmartSweeperKit', :path => '../'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'SDWebImage/Core', '~> 4.4.3'

  target 'TuyaSmartSweeperKit_Tests' do
    inherit! :search_paths

    
  end
end
